global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nextjs-api'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000'] # Use localhost on macOS/Windows
